### ISSUE TITLE
Unable to get an automation to work with toshiba_ac

### ISSUE THREAD

**Issue by TallGuy74** [h4de5/home-assistant-toshiba_ac#102]
I have the following automation that I want to work like this:

If the current temperature from the AC is above 19 (so 20), I want it to turn off.

```
id: '1672742060802'
alias: AC Off - Keuken
description: Turn AC in Kitchen off if temperature > 19
trigger:
  - platform: numeric_state
    entity_id: climate.keuken
    for:
      hours: 0
      minutes: 0
      seconds: 0
    attribute: current_temperature
    above: 19
condition:
  - condition: or
    conditions:
      - condition: device
        device_id: 617e11cc13a87d05e97934ee39c6b23d
        domain: climate
        entity_id: climate.keuken
        type: is_hvac_mode
        hvac_mode: heat
      - condition: device
        device_id: 617e11cc13a87d05e97934ee39c6b23d
        domain: climate
        entity_id: climate.keuken
        type: is_hvac_mode
        hvac_mode: auto
    enabled: false
action:
  - device_id: 617e11cc13a87d05e97934ee39c6b23d
    domain: climate
    entity_id: climate.keuken
    type: set_hvac_mode
    hvac_mode: 'off'
mode: restart
```

I have a second automation to turn the AC back on if the temperature drops below 19:

```
alias: AC On - Keuken
description: AC in Kitchen on if temperature < 19
trigger:
  - platform: numeric_state
    entity_id: climate.keuken
    for:
      hours: 0
      minutes: 15
      seconds: 0
    attribute: current_temperature
    below: 19
condition:
  - condition: and
    conditions:
      - condition: device
        device_id: 617e11cc13a87d05e97934ee39c6b23d
        domain: climate
        entity_id: climate.keuken
        type: is_hvac_mode
        hvac_mode: "off"
action:
  - device_id: 617e11cc13a87d05e97934ee39c6b23d
    domain: climate
    entity_id: climate.keuken
    type: set_hvac_mode
    hvac_mode: auto
mode: restart
```
For some reason, the automation doesn't do anything. Any idea what I'm doing wrong?
