### ISSUE TITLE
Homekit Integration for fan speed not working anymore

### ISSUE THREAD

**Issue by TJqt** [h4de5/home-assistant-toshiba_ac#175]
Hi, 

I discover an issue 2-3 weeks ago, 
i'm using, HA, and this integration ton control my Toshiba HAORI heat pump, and now, a can't anymore control my fan speed, it's working with HA control panel, but now not working with Apple HomeKit. 

have u change something recently which can create this bug ?

All is update in my HA configuration

**Comment by Pauw-R** [comment]
Hi,
I am noticing the same problem, everything works except controlling the fan speed.

**Comment by felixmueller** [comment]
Hi, same here. A fix would be awesome! Thank you so much!

**Comment by t-my** [comment]
Is this a HASS bridge or toshiba_ac bug? There are some similar reports in hass bridge repo: 

https://github.com/home-assistant/core/issues/120140#issuecomment-2200476899
https://github.com/home-assistant/core/issues/120140#issuecomment-2308666423

**Comment by crcorbett** [comment]
I'm also experiencing the same issue using the [Mitsubishi WF-RAC](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration) HACS integration.

The device shows up correctly within HomeAssistant (i.e. as a Climate device with fan + temperature controls) but only appears as a thermostat (without fan modes or speeds) in HomeKit.

```yml
hvac_modes:
  - "off"
  - auto
  - cool
  - dry
  - heat
  - fan_only
min_temp: 18
max_temp: 30
fan_modes:
  - auto
  - 1 Lowest
  - 2 Low
  - 3 High
  - 4 Highest
swing_modes:
  - Up/Down Auto
  - Highest
  - Middle
  - Normal
  - Lowest
  - 3D Auto
current_temperature: 22
temperature: 18
fan_mode: 4 Highest
swing_mode: 3D Auto
hvac_mode_state: "off"
horizontal_swing_mode: Center-Center
friendly_name: Bedroom Aircon
supported_features: 425
```

**Comment by h4de5** [comment]
I can't say what homekit does to control a HA climate device. 
the options you presented, seems not as this integration provides it. the fan modes and swing modes are coming from the api and returned as such: https://github.com/KaSroka/Toshiba-AC-control/blob/main/toshiba_ac/device/fcu_state.py#L126

```yaml
hvac_modes:
  - "off"
  - auto
  - cool
  - heat
  - dry
  - fan_only
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes:
  - Auto
  - Quiet
  - Low
  - Medium Low
  - Medium
  - Medium High
  - High
preset_modes:
  - Power 50
  - Power 75
  - Power 100
swing_modes:
  - "Off"
  - Swing Vertical
  - Swing Horizontal
  - Swing Vertical And Horizontal
current_temperature: 22
temperature: 23
fan_mode: Quiet
preset_mode: null
swing_mode: "Off"
merit_a_feature: "OFF"
merit_b_feature: "OFF"
air_pure_ion: "OFF"
self_cleaning: "OFF"
outdoor_temperature: null
icon: mdi:air-conditioner
friendly_name: Klima
supported_features: 441
```

as I do not use homeKit and as far as I know, do not state that it is supported at all, I am not sure what to do here?
